### ISSUE TITLE
Seed Poltician JSON into MONGODB

### ISSUE THREAD

**Issue by theotran** [cleong14/districtcrimes#25]

**Comment by aloha-fim** [comment]
complete.

# import json into mongo

⇒  mongod

⇒  mongoimport --db mongoose-demo --collection politicians --drop --file politician-house-dataset.json

⇒  mongo
MongoDB shell version: 3.2.1
connecting to: test

> use mongoose-demo
> switched to db mongoose-demo
> db.politicians.find()
