### ISSUE TITLE
Hard Code Politician Data

### ISSUE THREAD

**Issue by cleong14** [cleong14/districtcrimes#4]
Hard code Senate and House political data.
1. Person
2. District

**\* USE MONGO **\* (Experiment which is better)

**Comment by cleong14** [comment]
10 politicians done as of 3/26. 
about 70 more to go.

**Comment by cleong14** [comment]
1. Politician Name
2. Politician Party
3. District
4. Image of politician

**Comment by aloha-fim** [comment]
complete. Also, formatting errors complete with JSON validator
